import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { compile, loadDefault, type RuleSet } from "../src/rules.ts";
import { renderPolicy, scanRepo, type PolicyScan } from "../src/policy.ts";

/**
 * The policy document restates the config for people rather than for the
 * engine. Its whole value is that it cannot drift, so these assertions are
 * about what it must never omit, not about its wording.
 */

function emptyScan(): PolicyScan {
  return { files: 0, waivers: [], agents: [] };
}

function defaults(): RuleSet {
  return compile(loadDefault());
}

describe("what a finding does here", () => {
  it("says a finding changes nothing under the advisory default", () => {
    const doc = renderPolicy({ ...defaults(), failOn: "never" }, emptyScan());

    expect(doc).toContain("exits 0");
    expect(doc).not.toContain("fails the build");
  });

  it("says the build fails once failOn is error", () => {
    const doc = renderPolicy({ ...defaults(), failOn: "error" }, emptyScan());

    expect(doc).toContain("fails the build");
  });
});

describe("the document carries its own generated header", () => {
  it("marks itself generated and waives itself with a reason", () => {
    const doc = renderPolicy(defaults(), emptyScan());

    expect(doc).toContain("GENERATED by `plain-english policy`");
    // It names every banned term, so it has to waive itself, and the waiver has
    // to obey the rule it is documenting.
    expect(doc).toMatch(/plain-english-disable-file: \S/);
  });
});

describe("local deviations", () => {
  it("names a rule this repo turned off, with the stated reason", () => {
    const set = defaults();
    const rule = set.rules.find((r) => r.id === "load-bearing")!;
    rule.severity = "off";
    rule.reason = "structural engineering, the term is literal here";

    const doc = renderPolicy(set, emptyScan());

    expect(doc).toContain("load-bearing");
    expect(doc).toContain("structural engineering, the term is literal here");
  });

  it("says a deviation has no stated reason when it has none", () => {
    const set = defaults();
    set.rules.find((r) => r.id === "load-bearing")!.severity = "off";

    const doc = renderPolicy(set, emptyScan());

    expect(doc).toMatch(/load-bearing.*no reason given/i);
  });

  it("says so plainly when nothing was changed", () => {
    const doc = renderPolicy(defaults(), emptyScan());

    expect(doc).toMatch(/nothing.*changed|shipped ruleset unchanged/i);
  });
});

describe("waivers in the tree", () => {
  const scan: PolicyScan = {
    files: 2,
    agents: [],
    waivers: [
      {
        path: "docs/finance.md",
        line: 12,
        scope: "line",
        ids: ["leverage"],
        reason: "finance sense",
      },
      { path: "docs/legacy.md", line: 1, scope: "file", ids: [] },
    ],
  };

  it("lists a waiver with its path, line and reason", () => {
    const doc = renderPolicy(defaults(), scan);

    expect(doc).toContain("docs/finance.md");
    expect(doc).toContain("finance sense");
  });

  it("separates the ones that say nothing", () => {
    const doc = renderPolicy(defaults(), scan);
    const heading = doc.indexOf("## Waivers");
    const unexplained = doc.indexOf("docs/legacy.md");

    expect(heading).toBeGreaterThan(-1);
    expect(unexplained).toBeGreaterThan(heading);
    expect(doc).toMatch(/1 (waiver|of them) (says|say) nothing|no reason given/i);
  });
});

describe("what nothing here can reach", () => {
  it("names chat replies and subagents whatever the config says", () => {
    const doc = renderPolicy(defaults(), emptyScan());

    expect(doc).toContain("chat");
    expect(doc).toContain("Subagents");
  });

  it("does not claim an agent is covered when no hook is installed", () => {
    const doc = renderPolicy(defaults(), {
      ...emptyScan(),
      agents: [
        { id: "claude-code", installed: true, files: [".claude/settings.json"], problems: [] },
        { id: "codex", installed: false, files: [], problems: [] },
      ],
    });

    expect(doc).toContain(".claude/settings.json");
    expect(doc).toMatch(/codex.*not installed/i);
  });

  it("carries an installed agent's own warning through", () => {
    const doc = renderPolicy(defaults(), {
      ...emptyScan(),
      agents: [
        {
          id: "codex",
          installed: true,
          files: [".codex/config.toml"],
          problems: ["this folder is not trusted, so no hook runs"],
        },
      ],
    });

    expect(doc).toContain("this folder is not trusted, so no hook runs");
  });
});

describe("scanning a repository", () => {
  function fixture(): string {
    const root = mkdtempSync(resolve(tmpdir(), "pe-policy-"));
    mkdirSync(resolve(root, "docs"));
    writeFileSync(
      resolve(root, "docs", "finance.md"),
      [
        "# Finance",
        "",
        "<!-- plain-english-disable-next-line leverage: finance sense -->",
        "We leverage the ratio.",
      ].join("\n"),
    );
    writeFileSync(
      resolve(root, "docs", "legacy.md"),
      ["<!-- plain-english-disable-file -->", "", "Furthermore, we leverage it."].join("\n"),
    );
    writeFileSync(
      resolve(root, "docs", "howto.md"),
      [
        "To waive a rule:",
        "",
        "```markdown",
        "<!-- plain-english-disable-file -->",
        "```",
      ].join("\n"),
    );
    return root;
  }

  it("finds every waiver and reads its reason", () => {
    const scan = scanRepo(fixture(), defaults());
    const found = scan.waivers.map((w) => `${w.path}:${w.line} ${w.scope} ${w.reason ?? "-"}`);

    expect(found).toContain("docs/finance.md:3 line finance sense");
    expect(found).toContain("docs/legacy.md:1 file -");
  });

  it("does not count a directive quoted as documentation", () => {
    const scan = scanRepo(fixture(), defaults());

    expect(scan.waivers.map((w) => w.path)).not.toContain("docs/howto.md");
  });

  it("counts the files it read", () => {
    expect(scanRepo(fixture(), defaults()).files).toBe(3);
  });

  /**
   * The document waives itself, because it quotes every banned term. Counting
   * that waiver would make the report describe its own last run: write, scan,
   * find one more waiver, write again. `--check` would never agree with the
   * file on disk.
   */
  it("does not count the policy document itself", () => {
    const root = fixture();
    writeFileSync(
      resolve(root, "docs", "ai-writing-policy.md"),
      "<!-- plain-english-disable-file: policy document -->\n\n# AI writing policy\n",
    );

    const scan = scanRepo(root, defaults(), { skip: ["docs/ai-writing-policy.md"] });

    expect(scan.waivers.map((w) => w.path)).not.toContain("docs/ai-writing-policy.md");
  });

  it("is stable across a write, so --check can converge", () => {
    const root = fixture();
    const skip = { skip: ["docs/ai-writing-policy.md"] };
    const first = renderPolicy(defaults(), scanRepo(root, defaults(), skip));
    writeFileSync(resolve(root, "docs", "ai-writing-policy.md"), first);

    const second = renderPolicy(defaults(), scanRepo(root, defaults(), skip));

    expect(second).toBe(first);
  });
});

/**
 * The command, run through the built CLI.
 *
 * `--check` is the whole reason this document is worth generating rather than
 * writing, so a unit test on `renderPolicy` alone would miss the point.
 */
describe("the policy command", () => {
  const CLI = resolve(import.meta.dirname, "..", "dist", "cli.js");

  function repo(): string {
    const root = mkdtempSync(resolve(tmpdir(), "pe-policy-cli-"));
    mkdirSync(resolve(root, "docs"));
    writeFileSync(resolve(root, "docs", "a.md"), "The cache holds parsed results.\n");
    return root;
  }

  function run(root: string, args: string[]): { code: number; err: string } {
    try {
      execFileSync(process.execPath, [CLI, ...args], { cwd: root, stdio: "pipe" });
      return { code: 0, err: "" };
    } catch (e) {
      const err = e as { status?: number; stderr?: Buffer };
      return { code: err.status ?? -1, err: String(err.stderr ?? "") };
    }
  }

  it("writes the document, then agrees with itself", () => {
    const root = repo();

    expect(run(root, ["policy"]).code).toBe(0);
    expect(existsSync(resolve(root, "docs", "ai-writing-policy.md"))).toBe(true);
    expect(run(root, ["policy", "--check"]).code).toBe(0);
  });

  it("exits 1 and names the section when the document is edited", () => {
    const root = repo();
    run(root, ["policy"]);
    const path = resolve(root, "docs", "ai-writing-policy.md");
    writeFileSync(
      path,
      readFileSync(path, "utf8").replace("## Waivers in the tree", "## Waivers in the tree\n\nedited"),
    );

    const { code, err } = run(root, ["policy", "--check"]);

    expect(code).toBe(1);
    expect(err).toContain("is stale");
    expect(err).toContain("changed: Waivers in the tree");
  });

  it("exits 1 when the document was never written", () => {
    const { code, err } = run(repo(), ["policy", "--check"]);

    expect(code).toBe(1);
    expect(err).toContain("does not exist");
  });

  it("honours --out", () => {
    const root = repo();

    expect(run(root, ["policy", "--out", "POLICY.md"]).code).toBe(0);
    expect(existsSync(resolve(root, "POLICY.md"))).toBe(true);
  });
});
