#!/usr/bin/env bash
# Generated by `plain-english init`. Thin shim: all logic lives in the package,
# so upstream fixes arrive with an npm update instead of a copy-paste.
# Fail-open by contract; the CLI never exits non-zero on this path.
exec npx --no-install plain-english hook docs --agent claude-code
