#!/usr/bin/env node
/**
 * Build the Claude Code plugin's copy of the CLI.
 *
 * The plugin under integrations/claude-code-plugin/ is a mod: its hooks module
 * shells to this package's CLI for every decision, so the CLI has to travel
 * with the plugin. A plugin installed from a marketplace is copied as it is
 * in git, with no build step and no `npm install` of its own, so the copy is
 * committed: one bundled file with every dependency inlined, and the ruleset
 * beside it where `rules.ts` looks for it (`../rules/default.yml`).
 *
 * Why a bundle and not a lockfile. Claude Code does install a plugin's npm
 * packages from a lockfile, but a lockfile can only pin a version that is
 * already published, and this repository bumps its version before it
 * publishes. The bundle is built from the working tree, so the plugin at any
 * commit carries the linter at that commit, and `claude --plugin-dir` runs
 * the code being worked on.
 *
 * Runs as part of `npm run build`. CI's drift job diffs integrations/ after a
 * build, so a bundle somebody forgot to commit fails there with the same
 * message as a stale rendered doc. Pass --check to fail here instead when the
 * committed copy differs from a fresh build.
 */

import { build } from "esbuild";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const plugin = resolve(root, "integrations", "claude-code-plugin");
const entry = resolve(root, "dist", "cli.js");
const outFile = resolve(plugin, "dist", "cli.mjs");
const rulesFrom = resolve(root, "rules", "default.yml");
const rulesTo = resolve(plugin, "rules", "default.yml");
const packageTo = resolve(plugin, "package.json");

/**
 * The package.json the bundled CLI reads its own version from (`--version`,
 * `doctor`). Nothing else: no dependencies and no lockfile, so Claude Code
 * runs no install when it copies the plugin in. The version is the
 * repository's at build time, which the drift check holds in step.
 */
export function pluginPackageJson(version) {
  return (
    JSON.stringify(
      {
        name: "plain-english-claude-code-plugin",
        version,
        private: true,
        type: "module",
        description:
          "Carries the version the bundled plain-english CLI reports. Written by scripts/build-plugin.mjs.",
      },
      null,
      2,
    ) + "\n"
  );
}

const BANNER = [
  "// GENERATED by scripts/build-plugin.mjs from dist/cli.js. Do not edit.",
  "// The plain-english CLI with every dependency inlined, so the Claude Code",
  "// plugin runs it with nothing installed beside it.",
  "import { createRequire as __createRequire } from 'node:module';",
  "const require = __createRequire(import.meta.url);",
].join("\n");

/** Bundle the CLI into one ES module and return its text. */
export async function bundleCli() {
  if (!existsSync(entry)) {
    throw new Error("dist/cli.js is missing. Run `tsc -p tsconfig.json` first.");
  }
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    platform: "node",
    format: "esm",
    target: "node20",
    // Readable on purpose. The plugin directory's scanner reads what it
    // installs, and a reviewer should be able to as well.
    minify: false,
    legalComments: "none",
    banner: { js: BANNER },
    absWorkingDir: root,
    logLevel: "silent",
  });
  const file = result.outputFiles[0];
  if (!file) throw new Error("esbuild produced no output");
  return file.text;
}

const isMain =
  process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (isMain) {
  const check = process.argv.includes("--check");
  const fresh = await bundleCli();
  const rules = readFileSync(rulesFrom, "utf8");
  const { version } = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
  const pkg = pluginPackageJson(version);

  const stale = [];
  if (!existsSync(outFile) || readFileSync(outFile, "utf8") !== fresh) stale.push("dist/cli.mjs");
  if (!existsSync(rulesTo) || readFileSync(rulesTo, "utf8") !== rules) {
    stale.push("rules/default.yml");
  }
  if (!existsSync(packageTo) || readFileSync(packageTo, "utf8") !== pkg) stale.push("package.json");

  if (check) {
    if (stale.length) {
      process.stderr.write(
        `plain-english: the Claude Code plugin's copy is stale: ${stale.join(", ")}. ` +
          "Run `npm run build` and commit integrations/claude-code-plugin/.\n",
      );
      process.exit(1);
    }
    process.stdout.write("plugin: bundle and ruleset match the working tree\n");
  } else {
    mkdirSync(dirname(outFile), { recursive: true });
    mkdirSync(dirname(rulesTo), { recursive: true });
    writeFileSync(outFile, fresh, "utf8");
    copyFileSync(rulesFrom, rulesTo);
    writeFileSync(packageTo, pkg, "utf8");
    const kb = Math.round(Buffer.byteLength(fresh, "utf8") / 1024);
    process.stdout.write(
      `plugin: ${stale.length ? "wrote" : "unchanged"} integrations/claude-code-plugin/dist/cli.mjs (${kb} KB)\n`,
    );
  }
}
