/**
 * The launcher installed beside every project hook.
 *
 * Hook hosts disagree about their working directory, and `npx --no-install`
 * can still consult npm machinery before failing when the package is absent.
 * The launcher instead anchors itself to the repository that contains it,
 * tries two local layouts, then uses the already-installed global command.
 * It never downloads anything.
 */
export const HOOK_RUNNER = `#!/usr/bin/env node
// Generated by plain-english. Offline hook command resolver.
import { existsSync, readFileSync } from "node:fs";
import { spawn, spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const embeddedRoot = resolve(here, "../..");
const envRoot = process.env.PLAIN_ENGLISH_PROJECT_DIR ||
  process.env.CLAUDE_PROJECT_DIR || process.env.CODEX_PROJECT_DIR ||
  process.env.CURSOR_PROJECT_DIR || process.env.GEMINI_PROJECT_DIR ||
  process.env.QWEN_PROJECT_DIR || process.env.VIBE_PROJECT_DIR;
const roots = [...new Set([envRoot, embeddedRoot, process.cwd()].filter(Boolean))];
const args = process.argv.slice(2);

function isPackageRoot(root) {
  try {
    return JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")).name === "plain-english";
  } catch {
    return false;
  }
}

const signals = ["SIGTERM", "SIGINT", "SIGHUP"];

function run(command, commandArgs, cwd) {
  return new Promise((done) => {
    const child = spawn(command, commandArgs, {
      stdio: "inherit",
      cwd,
      // A separate POSIX process group lets cancellation reach the CLI and
      // anything it started. Windows uses taskkill's tree traversal instead.
      detached: process.platform !== "win32",
    });
    let relaying = false;

    const removeHandlers = () => {
      for (const signal of signals) process.removeListener(signal, handlers[signal]);
    };
    const exitWithSignal = (signal) => {
      removeHandlers();
      if (process.platform === "win32") {
        const numbers = { SIGHUP: 1, SIGINT: 2, SIGTERM: 15 };
        process.exit(128 + numbers[signal]);
      }
      process.kill(process.pid, signal);
    };
    const relay = (signal) => {
      if (relaying) return;
      relaying = true;
      if (child.pid !== undefined) {
        try {
          if (process.platform === "win32") {
            spawnSync("taskkill", ["/pid", String(child.pid), "/t", "/f"], {
              stdio: "ignore",
              windowsHide: true,
            });
          } else {
            process.kill(-child.pid, signal);
          }
        } catch (error) {
          if (!error || error.code !== "ESRCH") throw error;
        }
      }
      exitWithSignal(signal);
    };
    const handlers = Object.fromEntries(signals.map((signal) => [signal, () => relay(signal)]));

    for (const signal of signals) process.once(signal, handlers[signal]);
    child.once("error", (error) => {
      removeHandlers();
      done({ error });
    });
    child.once("exit", (status, signal) => {
      removeHandlers();
      if (signal) exitWithSignal(signal);
      else done({ status });
    });
  });
}

for (const root of roots) {
  const candidates = [
    ...(isPackageRoot(root) ? [resolve(root, "dist", "cli.js")] : []),
    resolve(root, "node_modules", "plain-english", "dist", "cli.js"),
  ];
  for (const cli of candidates) {
    if (!existsSync(cli)) continue;
    const result = await run(process.execPath, [cli, ...args], root);
    process.exit(result.status ?? 0);
  }
}

const globalRun = await run("plain-english", args, envRoot || process.cwd());
if (!globalRun.error) process.exit(globalRun.status ?? 0);
process.stderr.write(
  "plain-english hook could not find the repository package, a local dependency, or a global install.\\n" +
  "Run npm install in the repository or npm install -g plain-english.\\n",
);
process.exit(0);
`;

/** A generated runner path for one host. */
export function runnerPath(directory: string): string {
  return `${directory}/hooks/plain-english.mjs`;
}

/** Invoke a runner whose path is relative to the repository root. */
export function runnerCommand(path: string, channel: string, agent: string): string {
  return `node ${path} hook ${channel} --agent ${agent}`;
}
