/**
 * The launcher installed beside every project hook.
 *
 * Hook hosts disagree about their working directory, and `npx --no-install`
 * can still consult npm machinery before failing when the package is absent.
 * The launcher instead anchors itself to the repository that contains it,
 * tries two local layouts, then uses the already-installed global command.
 * It never downloads anything.
 */
export const HOOK_RUNNER = `#!/usr/bin/env node
// Generated by plain-english. Offline hook command resolver.
import { existsSync, readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const embeddedRoot = resolve(here, "../..");
const envRoot = process.env.PLAIN_ENGLISH_PROJECT_DIR ||
  process.env.CLAUDE_PROJECT_DIR || process.env.CODEX_PROJECT_DIR ||
  process.env.CURSOR_PROJECT_DIR || process.env.GEMINI_PROJECT_DIR ||
  process.env.QWEN_PROJECT_DIR || process.env.VIBE_PROJECT_DIR;
const roots = [...new Set([envRoot, embeddedRoot, process.cwd()].filter(Boolean))];
const args = process.argv.slice(2);

function isPackageRoot(root) {
  try {
    return JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")).name === "plain-english";
  } catch {
    return false;
  }
}

for (const root of roots) {
  const candidates = [
    ...(isPackageRoot(root) ? [resolve(root, "dist", "cli.js")] : []),
    resolve(root, "node_modules", "plain-english", "dist", "cli.js"),
  ];
  for (const cli of candidates) {
    if (!existsSync(cli)) continue;
    const run = spawnSync(process.execPath, [cli, ...args], { stdio: "inherit", cwd: root });
    process.exit(run.status ?? 0);
  }
}

const globalRun = spawnSync("plain-english", args, { stdio: "inherit", cwd: envRoot || process.cwd() });
if (!globalRun.error) process.exit(globalRun.status ?? 0);
process.stderr.write(
  "plain-english hook could not find the repository package, a local dependency, or a global install.\\n" +
  "Run npm install in the repository or npm install -g plain-english.\\n",
);
process.exit(0);
`;

/** A generated runner path for one host. */
export function runnerPath(directory: string): string {
  return `${directory}/hooks/plain-english.mjs`;
}

/** Invoke a runner whose path is relative to the repository root. */
export function runnerCommand(path: string, channel: string, agent: string): string {
  return `node ${path} hook ${channel} --agent ${agent}`;
}
