/**
 * `plain-english init --claude-code`
 *
 * The highest-friction step in the old design was a human hand-merging a
 * 50-line JSON blob out of a README into their own settings file. That is the
 * step most likely to be done wrong, and the one where an existing unrelated
 * hook gets clobbered.
 *
 * This merges by matcher, preserves every entry it did not add, and is
 * idempotent: running it twice changes nothing the second time.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { compile, loadDefault } from "./rules.ts";
import { renderPrompts } from "./render.ts";

const MARKER = "plain-english";

interface HookEntry {
  type: string;
  command?: string;
  prompt?: string;
  model?: string;
  timeout?: number;
  continueOnBlock?: boolean;
}
interface HookBlock {
  matcher: string;
  hooks: HookEntry[];
}
interface Settings {
  hooks?: { PreToolUse?: HookBlock[]; [k: string]: unknown };
  [k: string]: unknown;
}

const CHANNELS = [
  {
    channel: "docs",
    matcher: "Write|Edit|MultiEdit|NotebookEdit",
    script: "plain-english-docs.sh",
  },
  { channel: "github", matcher: "Bash", script: "plain-english-github.sh" },
  {
    channel: "issue",
    matcher: "mcp__linear__save_issue|mcp__linear__save_comment",
    script: "plain-english-issue.sh",
  },
] as const;

function shim(channel: string): string {
  return `#!/usr/bin/env bash
# Generated by \`plain-english init\`. Thin shim: all logic lives in the package,
# so upstream fixes arrive with an npm update instead of a copy-paste.
# Fail-open by contract; the CLI never exits non-zero on this path.
exec npx --no-install @nordscope/plain-english hook ${channel}
`;
}

const STARTER_CONFIG = `# Project config for plain-english.
# \`extends: default\` means you never fork the ruleset: you add your own
# vocabulary and exclusions, and upstream rule fixes still reach you.

version: 1
extends: default

# Terms that never trigger a finding. Put your domain vocabulary here.
allow: []

# Files the linter skips entirely. Anything that quotes the banned list as
# reference material belongs here.
exclude:
  - "docs/writing-style.md"
  - "CHANGELOG.md"

# Adjust individual rules without forking the file:
# rules:
#   - id: showcase
#     severity: warn
`;

/** True when a block was added by us, so re-running can replace it cleanly. */
function isOurs(entry: HookEntry): boolean {
  return (
    (entry.command ?? "").includes(MARKER) || (entry.prompt ?? "").includes(MARKER)
  );
}

export function mergeSettings(
  existing: Settings,
  blocks: HookBlock[],
): { settings: Settings; added: string[]; replaced: string[] } {
  const settings: Settings = { ...existing };
  settings.hooks = { ...(existing.hooks ?? {}) };
  const pre: HookBlock[] = [...(settings.hooks.PreToolUse ?? [])];
  const added: string[] = [];
  const replaced: string[] = [];

  for (const block of blocks) {
    const at = pre.findIndex((b) => b.matcher === block.matcher);
    if (at === -1) {
      pre.push(block);
      added.push(block.matcher);
      continue;
    }
    // Keep every entry that is not ours; swap ours for the current version.
    const keep = (pre[at]!.hooks ?? []).filter((h) => !isOurs(h));
    const had = (pre[at]!.hooks ?? []).length !== keep.length;
    pre[at] = { matcher: block.matcher, hooks: [...keep, ...block.hooks] };
    (had ? replaced : added).push(block.matcher);
  }

  settings.hooks.PreToolUse = pre;
  return { settings, added, replaced };
}

export interface InitOptions {
  root: string;
  dryRun?: boolean;
  model?: string;
}

export function initClaudeCode(opts: InitOptions): number {
  const { root, dryRun = false } = opts;
  const model = opts.model ?? "claude-sonnet-5";
  const hooksDir = resolve(root, ".claude", "hooks");
  const settingsPath = resolve(root, ".claude", "settings.json");
  const configPath = resolve(root, ".plain-english.yml");
  const prompts = renderPrompts(compile(loadDefault()));
  const planned: string[] = [];

  const blocks: HookBlock[] = CHANNELS.map((c) => ({
    matcher: c.matcher,
    hooks: [
      { type: "command", command: `$CLAUDE_PROJECT_DIR/.claude/hooks/${c.script}` },
      {
        type: "prompt",
        prompt: (prompts[c.channel] ?? "").replaceAll("{{PROJECT_DIR}}", root),
        model,
        timeout: 30,
        continueOnBlock: true,
      },
    ],
  }));

  let existing: Settings = {};
  if (existsSync(settingsPath)) {
    try {
      existing = JSON.parse(readFileSync(settingsPath, "utf8")) as Settings;
    } catch (e) {
      process.stderr.write(
        `plain-english: ${relative(root, settingsPath)} is not valid JSON, refusing to touch it\n` +
          `  ${e instanceof Error ? e.message : String(e)}\n`,
      );
      return 2;
    }
  }

  const preserved = (existing.hooks?.PreToolUse ?? []).reduce(
    (n, b) => n + (b.hooks ?? []).filter((h) => !isOurs(h)).length,
    0,
  );
  const { settings, added, replaced } = mergeSettings(existing, blocks);

  planned.push(
    `${existsSync(settingsPath) ? "update" : "create"} ${relative(root, settingsPath)}` +
      ` (added: ${added.join(", ") || "none"}; replaced: ${replaced.join(", ") || "none"};` +
      ` preserved ${preserved} unrelated hook${preserved === 1 ? "" : "s"})`,
  );
  for (const c of CHANNELS) planned.push(`create ${relative(root, resolve(hooksDir, c.script))}`);
  if (!existsSync(configPath)) planned.push(`create ${relative(root, configPath)}`);

  if (dryRun) {
    process.stdout.write("plain-english init --dry-run\n\n");
    for (const p of planned) process.stdout.write(`  ${p}\n`);
    process.stdout.write("\nNothing was written.\n");
    return 0;
  }

  mkdirSync(hooksDir, { recursive: true });
  for (const c of CHANNELS) {
    const path = resolve(hooksDir, c.script);
    writeFileSync(path, shim(c.channel), "utf8");
    chmodSync(path, 0o755);
  }
  mkdirSync(dirname(settingsPath), { recursive: true });
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n", "utf8");
  if (!existsSync(configPath)) writeFileSync(configPath, STARTER_CONFIG, "utf8");

  for (const p of planned) process.stdout.write(`  ${p}\n`);
  process.stdout.write(
    "\nDone. Add a short writing-style section to your CLAUDE.md pointing at\n" +
      "docs/writing-style.md, then try: plain-english lint .\n",
  );
  return 0;
}
