/**
 * The policy document: what this repository enforces, written for people.
 *
 * `render` emits the artifacts that restate the shipped ruleset. This emits the
 * one artifact that restates a *project's* effective config, so it belongs to
 * the consumer repository rather than to this one. A team adopting a linter
 * writes this document by hand and then lets it drift from the config it
 * describes. Generating it removes the gap by construction.
 *
 * Two sections make it more than a prettier `.plain-english.yml`: what the
 * project changed and why, and what nothing in the setup can reach. A
 * hand-written policy omits the second one every time.
 */

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { extname, relative, resolve } from "node:path";
import { directivesIn, type WaiverScope } from "./lint.ts";
import { matchesAny } from "./glob.ts";
import { humanise, markdownTableCode } from "./render.ts";
import { loadDefault, type ReadabilityRule, type Rule, type RuleSet } from "./rules.ts";
import { PROFILES } from "./agents/registry.ts";
import { hasOurEntries } from "./init.ts";

/** One suppression directive, located in the tree. */
export interface Waiver {
  /** Repository-relative, with forward slashes. */
  path: string;
  line: number;
  scope: WaiverScope;
  /** The rules it silences. Empty means every rule. */
  ids: string[];
  reason?: string;
}

/** Which agent hooks are actually on disk, and what is wrong with them. */
export interface DetectedAgent {
  id: string;
  installed: boolean;
  /** The config files carrying a plain-english entry. */
  files: string[];
  /** Stable requirements that can stop an installed hook from running. */
  problems: string[];
}

/**
 * Trust requirements belong in a checked-in policy; one machine's current
 * trust decisions do not. `doctor` reports that local state separately.
 */
const AGENT_REQUIREMENTS: Partial<Record<string, string>> = {
  copilot: "repository hooks require folder trust in prompt mode",
  codex: "requires project trust and review of the current hook definition",
  cursor: "requires a trusted workspace",
  vibe: "requires a trusted folder",
  gemini: "requires project hook trust",
  qwen: "requires project hook trust",
};

/**
 * Everything the document needs that is not in the ruleset.
 *
 * Deliberately not here: how many files were read. That number counts
 * everything on disk, including files git ignores, so a scratch note in one
 * person's working tree made the document differ from the same document
 * generated in a fresh checkout, and `--check` failed in CI for a file CI could
 * not see. Any figure this document prints has to be a property of the
 * repository rather than of somebody's working directory.
 */
export interface PolicyScan {
  waivers: Waiver[];
  agents: DetectedAgent[];
}

/**
 * A repository-relative path as this module keys them.
 *
 * Windows `relative` returns backslashes, so a caller comparing its own path
 * against a scan result has to agree on one spelling. Exported because the CLI
 * builds the skip list for the policy document itself.
 */
export function toPosix(path: string): string {
  return path.split("\\").join("/");
}

const MARKDOWN = new Set([".md", ".markdown", ".mdx"]);
const SKIP = new Set(["node_modules", ".git", "dist"]);

const BANNER = [
  "<!-- GENERATED by `plain-english policy`. Do not edit. -->",
  // The document quotes every banned term as reference material, so it waives
  // itself. The reason is not decoration: `unexplained-suppression` would
  // otherwise report the policy document for breaking the rule it documents.
  "<!-- plain-english-disable-file: policy document, quotes every banned term -->",
].join("\n");

/**
 * A checked-in policy describes the repository, not one contributor's private
 * agent setup. Git-ignored hook files can exist on one machine and disappear
 * in CI, which would otherwise make `policy --check` impossible to satisfy in
 * both places. Outside a git worktree there is no ignored set, so count the
 * file normally.
 */
function isGitIgnored(root: string, file: string): boolean {
  try {
    execFileSync("git", ["check-ignore", "-q", "--", file], {
      cwd: root,
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(entry.name)) continue;
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (MARKDOWN.has(extname(entry.name).toLowerCase())) out.push(full);
  }
  return out;
}

/**
 * Which agent configs exist here, and whether they are ours.
 *
 * The same walk `doctor` does. A policy that claims an agent is covered when
 * its hook file was never written would be worse than no policy, so this reads
 * the disk rather than the list of agents `init` knows about.
 */
export function detectAgents(root: string): DetectedAgent[] {
  return PROFILES.map((profile) => {
    const files = new Set<string>();
    for (const file of profile.plan({ prompts: {}, model: "" }).config) {
      if (file.scope !== "user" && isGitIgnored(root, file.path)) continue;
      const path = resolve(root, file.path);
      let ours = false;
      try {
        ours = hasOurEntries(readFileSync(path, "utf8"), file);
      } catch {
        continue; // missing or unreadable counts as not installed
      }
      if (ours) files.add(file.path);
    }
    return {
      id: profile.id,
      installed: files.size > 0,
      files: [...files],
      problems: files.size && AGENT_REQUIREMENTS[profile.id] ? [AGENT_REQUIREMENTS[profile.id]!] : [],
    };
  });
}

export interface ScanOptions {
  /**
   * Repository-relative paths to leave out, always the policy document itself.
   *
   * The document waives every rule, because it quotes every banned term. Left
   * in, the report would describe its own last run and grow a waiver each time,
   * so `--check` could never agree with the file on disk.
   */
  skip?: string[];
}

/** Read the tree: every waiver, and every agent hook that is really there. */
export function scanRepo(root: string, set: RuleSet, options: ScanOptions = {}): PolicyScan {
  const waivers: Waiver[] = [];
  const skip = new Set(options.skip ?? []);

  for (const file of walk(resolve(root))) {
    const rel = toPosix(relative(root, file));
    if (skip.has(rel)) continue;
    if (set.exclude.length && matchesAny(rel, set.exclude)) continue;

    let text: string;
    try {
      text = readFileSync(file, "utf8");
    } catch {
      continue; // an unreadable file is not a waiver
    }
    for (const d of directivesIn(text)) {
      const waiver: Waiver = { path: rel, line: d.line, scope: d.scope, ids: d.ids };
      if (d.reason) waiver.reason = d.reason;
      waivers.push(waiver);
    }
  }

  waivers.sort((a, b) => a.path.localeCompare(b.path) || a.line - b.line);
  return { waivers, agents: detectAgents(root) };
}

/** What a finding actually causes, in the words of the setting that causes it. */
function consequence(set: RuleSet): string {
  if (set.failOn === "error") {
    return (
      "A blocking finding fails the build, and an agent hook refuses the write. A warning " +
      "is reported and the command still exits 0."
    );
  }
  if (set.failOn === "warn") {
    return (
      "Every finding, warnings included, fails the build, and an agent hook refuses the " +
      "write. This is the strictest setting available."
    );
  }
  return (
    "Nothing, by itself. Every finding is reported and the command exits 0, so a label " +
    "reading `block` names the rule's tier and not the outcome. Blocking is opt-in: set " +
    "`failOn: error` in `.plain-english.yml` to make it real."
  );
}

function plural(n: number, word: string): string {
  return n === 1 ? word : `${word}s`;
}

function tier(rule: Rule): string {
  return rule.severity === "warn" ? "warn" : "block";
}

function deviations(set: RuleSet): string[] {
  const shipped = new Map<string, string>();
  for (const r of DEFAULTS().rules) shipped.set(r.id, r.severity);
  for (const r of DEFAULTS().readability) shipped.set(r.id, r.severity);

  const out: string[] = [];
  const changed = (r: Rule | ReadabilityRule): boolean =>
    shipped.has(r.id) && shipped.get(r.id) !== r.severity;

  for (const r of [...set.rules, ...set.readability]) {
    if (!changed(r)) continue;
    const from = shipped.get(r.id)!;
    const why = r.reason ? r.reason : "_no reason given_";
    out.push(`- \`${r.id}\`: \`${from}\` to \`${r.severity}\`. ${why}`);
  }
  return out;
}

/**
 * The shipped ruleset, for comparison. Read once: the document is generated in
 * a single pass and every rule asks the same question of it.
 */
let cached: RuleSet | undefined;
function DEFAULTS(): RuleSet {
  cached ??= loadDefault();
  return cached;
}

/** The policy document. Pure: every fact comes from `set` or `scan`. */
export function renderPolicy(set: RuleSet, scan: PolicyScan): string {
  const out: string[] = [];
  out.push(BANNER, "");
  out.push("# AI writing policy", "");
  out.push(
    "What this repository checks in text that other people read, and what it does about " +
      "a finding. Generated from the ruleset and `.plain-english.yml` by " +
      "`plain-english policy`, so it cannot drift from the configuration it describes.",
    "",
  );

  out.push("## What a finding does here", "");
  out.push(consequence(set), "");

  out.push("## Where it runs", "");
  if (!scan.agents.length) {
    out.push(
      "No agent hooks were detected. The command-line linter is the only channel, and it " +
        "runs when somebody runs it.",
      "",
    );
  } else {
    out.push("| Agent | Hook | Notes |");
    out.push("|---|---|---|");
    for (const a of scan.agents) {
      const where = a.installed ? a.files.map((f) => `\`${f}\``).join(", ") : "not installed";
      const notes = a.problems.length ? a.problems.join("; ") : a.installed ? "" : "no hook runs";
      out.push(`| ${a.id} | ${where} | ${notes} |`);
    }
    out.push("");
  }

  const live = set.rules.filter((r) => r.severity !== "off");
  const blocking = live.filter((r) => r.severity === "error");
  out.push("## The rules in force", "");
  out.push(
    `${live.length} word and punctuation rules, ${blocking.length} of them blocking, plus ` +
      `${set.structures.length} sentence shapes judged by a model and ` +
      `${set.readability.filter((r) => r.severity !== "off").length} readability rules.`,
    "",
  );
  out.push("| Term | Tier | Instead |");
  out.push("|---|---|---|");
  for (const rule of live) {
    out.push(`| ${markdownTableCode(humanise(rule))} | \`${tier(rule)}\` | ${rule.message ?? ""} |`);
  }
  out.push("");

  out.push("## What this repository changed", "");
  const changes = deviations(set);
  if (changes.length) {
    out.push("Severities that differ from the shipped ruleset:", "");
    out.push(...changes, "");
  } else {
    out.push("Nothing. The shipped ruleset is unchanged here.", "");
  }
  // Split by reach, because the two are very different promises. An unscoped
  // entry silences the whole ruleset on any line it touches, and a reader of
  // this document deserves to see which entries do that.
  const wide = set.allow.filter((a) => !a.rules?.length);
  const scoped = set.allow.filter((a) => a.rules?.length);
  if (wide.length) {
    out.push(
      `Vocabulary that suppresses every rule on a matching line (${wide.length} ` +
        `patterns): ${wide.map((a) => `\`${a.pattern}\``).join(", ")}.`,
      "",
    );
  }
  if (scoped.length) {
    out.push("Vocabulary declared to named rules only:", "");
    for (const a of scoped) {
      out.push(
        `- \`${a.pattern}\` for ${a.rules!.map((r) => `\`${r}\``).join(", ")}` +
          (a.semantic ? ", and to the semantic layer" : "") +
          ".",
      );
    }
    out.push("");
  }
  if (set.exclude.length) {
    out.push(
      `Files skipped entirely: ${set.exclude.map((e) => `\`${e}\``).join(", ")}.`,
      "",
    );
  }

  out.push("## Waivers in the tree", "");
  const explained = scan.waivers.filter((w) => w.reason);
  const silent = scan.waivers.filter((w) => !w.reason);
  if (!scan.waivers.length) {
    out.push("No file waives a rule.", "");
  } else {
    const spread = new Set(scan.waivers.map((w) => w.path)).size;
    const count = `${scan.waivers.length} ${plural(scan.waivers.length, "waiver")}`;
    const quiet = silent.length
      ? `, and ${silent.length} of them ${silent.length === 1 ? "says" : "say"} nothing about why`
      : ", and every one of them says why";
    out.push(`${count} in ${spread} ${plural(spread, "file")}${quiet}.`, "");
    if (explained.length) {
      out.push("| Where | Scope | Rules | Reason |");
      out.push("|---|---|---|---|");
      for (const w of explained) {
        out.push(
          `| \`${w.path}:${w.line}\` | ${w.scope} | ${w.ids.length ? w.ids.join(", ") : "all"} | ${w.reason} |`,
        );
      }
      out.push("");
    }
    if (silent.length) {
      out.push("### Waivers with no stated reason", "");
      out.push(
        "Each of these silences a rule without saying why, so the next reader cannot tell " +
          "a considered exception from a rule somebody found annoying. Add the reason after " +
          "a colon.",
        "",
      );
      for (const w of silent) {
        out.push(
          `- \`${w.path}:${w.line}\` (${w.scope}, ${w.ids.length ? w.ids.join(", ") : "all rules"})`,
        );
      }
      out.push("");
    }
  }

  out.push("## What nothing here can reach", "");
  out.push(
    "This section used to say that a chat reply is not a tool call, so nothing sees one. " +
      "That is no longer true everywhere, and where it is still true it is worth naming " +
      "per agent rather than as one flat claim.",
    "",
  );
  out.push("| Agent | Chat gate | Reaches subagents |");
  out.push("|---|---|---|");
  for (const a of scan.agents) {
    const profile = PROFILES.find((p) => p.id === a.id);
    const gated = Boolean(profile?.emitChat);
    const state = !a.installed
      ? "not installed"
      : gated
        ? "on the stop events"
        : "**none**, no event carries the reply";
    out.push(`| ${a.id} | ${state} | ${gated && a.installed ? "yes" : "no"} |`);
  }
  out.push("");
  out.push(
    "An output style shapes a reply before it exists and cannot be measured. A stop hook " +
      "reads the finished reply and can hand a finding back to the model, which is the " +
      "closest thing to a gate this channel has. Under `failOn: never` it reports and " +
      "holds up nothing.",
    "",
  );
  out.push(
    "A style reaches the main conversation and a fork, which inherits the parent's system " +
      "prompt. It does not reach a subagent, which runs its own. Where the table above " +
      "says a chat gate is installed, the subagent gap is covered by that instead.",
    "",
  );
  out.push(
    "`plain-english lint --chat` reads what was actually said, from the transcripts each " +
      "agent writes locally, and splits the rate by main loop against subagent. It is " +
      "local only: a transcript holds whatever passed through a tool.",
    "",
  );
  out.push(
    `The ${set.structures.length} sentence shapes need a model to judge them, so they are ` +
      "checked by Claude Code's prompt hooks and by Vibe's optional local judge. For " +
      "Copilot, Codex, Cursor, Gemini and Qwen they are guidance in `AGENTS.md`; no " +
      "runtime model judge is installed.",
    "",
  );
  out.push(
    "The rules describe how models wrote in 2024 and 2025. Vendors suppress known tells, " +
      "so this list decays and needs maintenance.",
    "",
  );

  return out.join("\n");
}
