/**
 * Generate every artifact that restates the rules.
 *
 * The old design maintained the same list in four shapes: a regex in three
 * shell scripts, a prose list inside three prompt bodies, a human-readable
 * table in a markdown file, and a summary in the project instructions. Nothing
 * checked that they agreed, and they did not.
 *
 * Here, only rules/default.yml is written by hand. Everything else is emitted
 * from it and checked by CI.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { inLevel } from "./rules.ts";
import type { ReadabilityRule, Rule, RuleSet, Structure } from "./rules.ts";

const BANNER =
  "<!-- GENERATED by `plain-english render` from rules/default.yml. Do not edit. -->\n" +
  // This file lists every banned term as reference material, so it necessarily
  // trips almost every rule. Carrying its own directive means an adopter does
  // not have to discover that and add an `exclude` entry by hand.
  "<!-- plain-english-disable-file: reference material, lists every banned term -->";
const TXT_BANNER =
  "# GENERATED by `plain-english render` from rules/default.yml. Do not edit.";

/**
 * Turn a rule's regex back into something a human can read.
 *
 *   seamless(ly)?              ->  seamless[ly]
 *   delv(e|es|ed|ing)          ->  delv(e/es/ed/ing)
 *   cutting[- ]edge            ->  cutting-edge
 *   a|b                        ->  a, b
 *
 * An optional group has to be rendered as optional. Collapsing `(ly)?` to `ly`
 * turned "seamless(ly)?" into "seamlessly" in the first generated table, which
 * told the reader the bare word was allowed.
 */
export function humanise(rule: Rule): string {
  const m = rule.match;
  if (m === "—") return "em dash (—)";
  if (m === "\\s–\\s") return "en dash used as a sentence break";

  // Split on alternation at depth 0 only, so `(a|b)` stays intact.
  const alternatives: string[] = [];
  let depth = 0;
  let current = "";
  for (let i = 0; i < m.length; i++) {
    const ch = m[i]!;
    if (ch === "\\") {
      current += ch + (m[++i] ?? "");
      continue;
    }
    if (ch === "(") depth++;
    if (ch === ")") depth--;
    if (ch === "|" && depth === 0) {
      alternatives.push(current);
      current = "";
      continue;
    }
    current += ch;
  }
  alternatives.push(current);

  const render = (alt: string): string =>
    alt
      .replace(/\(\?[=!:][^)]*\)/g, "") // lookarounds carry no reader value
      .replace(/\(([^()]*)\)\?/g, (_, inner: string) => `[${inner.split("|").join("/")}]`)
      .replace(/\(([^()]*)\)/g, (_, inner: string) => {
        const opts = inner.split("|").filter(Boolean);
        return opts.length > 1 ? `(${opts.join("/")})` : inner;
      })
      .replace(/\[- \]/g, "-")
      // A repeated character class stands in for "any word here". The reader
      // needs the shape, not the class: "in a hasty manner" and "in a careless
      // manner" are the same rule, and no list of adjectives would describe it.
      .replace(/\[[^\]]+\]\+/g, "...")
      // An optional literal ("it'?s" catches both spellings) reads as the
      // straight form. Leaving the "?" in makes the table look like regex.
      .replace(/([^)\]?])\?/g, "$1")
      .replace(/\\b/g, "")
      .replace(/\\s\+?/g, " ")
      .replace(/\\([.\-'])/g, "$1")
      .replace(/\\/g, "")
      .replace(/\s+/g, " ")
      .trim();

  return alternatives.map(render).filter(Boolean).join(", ");
}

function severityMark(rule: Rule): string {
  return rule.severity === "warn" ? "warn" : "block";
}

/**
 * Prose for one readability rule, built from its own fields so the threshold
 * and the exemption count can never drift from the ruleset.
 */
function readabilityDescription(r: ReadabilityRule): string {
  if (r.kind === "unexplained-suppression") {
    return (
      "Fires on a suppression directive that does not say why. Write the reason after " +
      "a colon: `<!-- plain-english-disable leverage: finance sense -->`. This is the " +
      "one rule an in-file directive cannot silence, because `disable-file` covers the " +
      "whole document and would cover the reasonless `disable-file` reporting it. Turn " +
      "it off in config, or match the line with `allow`."
    );
  }
  if (r.kind === "long-sentence") {
    return (
      `Fires past ${r.maxWords} words. Set generously: a long sentence carrying one ` +
      `idea is fine, and the usual fault at that length is three ideas in one.`
    );
  }
  if (r.kind === "reply-length") {
    return (
      `Fires past ${r.maxWords} words of prose in one reply. Quoted output, tables and ` +
      "code do not count, because quoting the line a claim rests on outranks brevity. " +
      "The number is measured rather than chosen: across seven days of transcripts the " +
      "90th-percentile reply was 254 words, and the shortest reply a reader complained " +
      "about was 264."
    );
  }
  if (r.kind === "reader-load") {
    return (
      `Fires past ${r.maxTerms} distinct backticked names in one reply: files, config ` +
      "keys, flags. Counted absolutely and never as a rate, because the rate points the " +
      "wrong way. In the replies readers complained about, jargon density was lower than " +
      "in long replies generally; what separated them was the total. Five terms in a " +
      "sixty-word answer is over quickly. Eighteen across five hundred words is carried " +
      "to the end."
    );
  }
  const known = r.known?.length
    ? ` ${r.known.length} names a reader already has, such as JSON and GitHub, are exempt.`
    : "";
  const emphasis = r.emphasis?.length
    ? ` So is a word shouted for emphasis: ${r.emphasis.length} common ones are listed, ` +
      "and anything longer ending in -ed, -ing, -ly, -tion or -able is read as a word " +
      "rather than an acronym."
    : "";
  return (
    "Fires on an acronym of three or more letters, or a camel-cased name, used before " +
    "it is explained. First use only: repeating a term is not the problem. A term that " +
    'arrives with its gloss is never reported, so "is called X", "known as X", ' +
    '"X stands for Y" and a parenthetical expansion in either order all pass.' +
    known +
    emphasis +
    " A project adds its own vocabulary through `known` in `.plain-english.yml`, or " +
    "through an `allow` entry scoped to this rule."
  );
}

/** docs/writing-style.md */
export function renderWritingStyle(set: RuleSet): string {
  const out: string[] = [];
  out.push(BANNER, "");
  out.push(`# ${set.meta.title}`, "");
  if (set.meta.intro) out.push(set.meta.intro, "");

  out.push("Two severities:", "");
  out.push("| Severity | Effect |");
  out.push("|---|---|");
  out.push("| `block` | The write is refused and the CLI exits non-zero. |");
  out.push(
    "| `warn` | Reported, never blocks. Used for terms with a real technical sense. |",
  );
  out.push("");

  out.push("## Words and phrases", "");
  out.push("| Term | Severity | Instead | Why |");
  out.push("|---|---|---|---|");
  for (const rule of set.rules) {
    if (rule.severity === "off") continue;
    const why = rule.link ? `[notes](${rule.link})` : "";
    out.push(
      `| ${humanise(rule)} | \`${severityMark(rule)}\` | ${rule.message ?? ""} | ${why} |`,
    );
  }
  out.push("");

  const withExceptions = set.rules.filter((r) => r.unless?.length && r.severity !== "off");
  if (withExceptions.length) {
    out.push("## Exceptions", "");
    out.push(
      "These terms have a legitimate technical or domain sense. The listed uses never trigger a finding.",
      "",
    );
    for (const rule of withExceptions) {
      out.push(`- **${rule.id}**: ${rule.unless!.map((u) => `\`${u}\``).join(", ")}`);
    }
    out.push("");
  }

  out.push("## Sentence shapes", "");
  out.push(
    "A word list cannot reach these. They are judged by the semantic layer, or by you.",
    "",
  );
  for (const s of set.structures) {
    out.push(`### ${s.name}`, "");
    out.push(s.description, "");
    if (s.bad) out.push(`Bad: ${s.bad}`);
    if (s.good) out.push(`Good: ${s.good}`);
    out.push("");
  }

  // The readability rules ship `link: ...writing-style.md#readability` and the
  // suppression rule ships `#suppressions`, so these two sections are what
  // those anchors resolve to. Without them every such finding printed a dead
  // link. They are split because they answer different questions: one reads the
  // shape of a sentence, the other reads what the author did about a finding.
  const live = set.readability.filter((r) => r.severity !== "off");
  const shape = live.filter((r) => r.kind !== "unexplained-suppression");
  const waivers = live.filter((r) => r.kind === "unexplained-suppression");

  if (shape.length) {
    out.push("## Readability", "");
    out.push(
      "These read the shape of a sentence, so there is no term to match. All are warnings.",
      "",
    );
    for (const r of shape) {
      out.push(`### ${r.id}`, "");
      out.push(readabilityDescription(r), "");
      if (r.message) out.push(`Instead: ${r.message}`, "");
    }
  }

  // The chat channel gets its own heading because its rules apply to one reply
  // and to nothing else, and because the `link` on each of them points here.
  const limits = (set.chat.limits ?? []).filter((r) => r.severity !== "off");
  if (limits.length) {
    out.push("## Chat", "");
    out.push(
      "These apply to a reply in the chat window and to nothing else. A document that " +
        "runs long is doing its job; a reply that runs long is the complaint readers " +
        "make most often. Both are checked on the stop event, and both can be waived " +
        "by the judge when the reader asked for the depth.",
      "",
    );
    for (const r of limits) {
      out.push(`### ${r.id}`, "");
      out.push(readabilityDescription(r), "");
      if (r.message) out.push(`Instead: ${r.message}`, "");
    }
  }

  if (waivers.length) {
    out.push("## Suppressions", "");
    out.push(
      "Silencing a rule is a decision, and the next reader cannot review a decision with no stated reason.",
      "",
    );
    for (const r of waivers) {
      out.push(`### ${r.id}`, "");
      out.push(readabilityDescription(r), "");
      if (r.message) out.push(`Instead: ${r.message}`, "");
    }
  }

  out.push("## What is never scanned", "");
  out.push(
    "The document is parsed, and only prose text is matched. Everything below is blanked first, so a banned term inside any of it is not a finding.",
    "",
  );
  out.push("- Fenced and indented code, and inline code spans");
  out.push("- Inline `<code>`, `<pre>`, `<kbd>`, `<samp>`, `<var>` and `<tt>` pairs");
  out.push("- Raw HTML blocks, and HTML comments");
  out.push("- YAML and TOML frontmatter");
  out.push("- Tables, whose cells hold identifiers far more often than prose");
  out.push("- Blockquotes, which are someone else's words");
  out.push("- Link destinations, link reference definitions, autolinks and bare URLs");
  out.push("");
  out.push(
    "Link text is prose and is checked. Footnote definitions are prose and are checked.",
    "",
  );
  out.push("## Suppressing a finding", "");
  out.push("Every form takes a reason after a colon, and is reported without one.", "");
  out.push("```markdown");
  out.push("<!-- plain-english-disable-next-line leverage: finance sense -->");
  out.push("<!-- plain-english-disable-file: reference material, lists every banned term -->");
  out.push("```");
  out.push("");
  out.push(
    "Or add the path to `exclude` in `.plain-english.yml`, or lower the rule to `severity: warn`.",
    "",
  );

  return out.join("\n");
}

function ruleListForPrompt(set: RuleSet): string {
  const blocking = set.rules
    .filter((r) => r.severity === "error")
    .map((r) => humanise(r));
  return blocking.join("; ");
}

function structureListForPrompt(set: RuleSet): string {
  return set.structures.map((s) => `${s.name} (${s.description.replace(/\s+/g, " ").trim()})`).join("; ");
}

const JSON_CONTRACT =
  'Respond with ONLY JSON, nothing else: {"ok": true} if it passes, or ' +
  '{"ok": false, "reason": "<quote the offending substring verbatim, then give a one-line plain rewrite>"} if it does not.';

/**
 * Calibration.
 *
 * Asked to find a list of patterns, a model finds patterns. Observed in this
 * project before these rules existed: one document was refused twelve times in
 * a row; on two of those the model flagged wording it had itself proposed one
 * turn earlier; on another it reasoned to the conclusion that no violation
 * existed and returned a refusal anyway.
 *
 * The three rules below target those failures directly. The self-consistency
 * rule is the important one: a verdict whose own reasoning says the text is
 * fine must be a pass.
 */
const CALIBRATION =
  "CALIBRATION. Most text you see is fine. A pass is the normal answer, and returning one is " +
  'a correct, complete job. Do not go looking for something to flag.\n\n' +
  "SELF-CONSISTENCY. If your reasoning arrives at the conclusion that the text is acceptable, " +
  'you MUST return {"ok": true}. Never return a failure whose reason says the content passes, ' +
  "says no violation was found, or hedges about whether a rule applies. A failure means you " +
  "located a specific, quotable problem and are certain about it.\n\n" +
  "ONE FLAG. Report the single clearest problem. Do not accumulate borderline observations, " +
  "and do not flag a phrase you would accept if you saw it in a well-edited document.\n\n" +
  "NO SECOND-GUESSING A REWRITE. If the text reads as a plain, direct statement of fact, it " +
  "passes, even if you can imagine a different phrasing.";

const PRECISION =
  "Before writing your reason, quote the exact substring from the text that triggered it. " +
  "If you cannot find that substring verbatim in the text, do not flag it. " +
  "The deterministic linter has already checked every banned term and blocked the write if it " +
  "found one, so a term reaching you has already passed that check: judge SENTENCE SHAPES, and " +
  "flag a listed term only when it is genuinely being used as the tell rather than as ordinary " +
  "domain vocabulary. " +
  "Do NOT flag: exact technical identifiers that must stay verbatim, text inside code blocks or " +
  "inline code, quoted third-party text in blockquotes, URLs, normal concise writing, or " +
  "stylistic choices outside this list. Be precise, not paranoid.";

/** Characters a pattern may hold and still be read as plain words. */
const LITERAL_TERM = /^[A-Za-z0-9][A-Za-z0-9 ._'-]*$/;

/**
 * The words behind an `allow` pattern, for a reader who is not a regex engine.
 *
 * `\b(Deal|Contact)\b` is four characters of syntax around two ordinary
 * nouns, and a model told to accept "Deal" needs the noun. A pattern that is
 * not a plain alternation of literals cannot be turned back into words, so it
 * is quoted as itself and labelled.
 */
export function vocabularyTerms(pattern: string): string[] {
  const stripped = pattern.replaceAll("\\b", "").trim();
  const group = /^\((?:\?:)?([^()]+)\)$/.exec(stripped);
  const parts = (group ? group[1]! : stripped).split("|");
  const out: string[] = [];
  for (const part of parts) {
    // "Deals?" is one word with an optional plural, which is the commonest
    // shape in a real config.
    const base = part.replace(/s\?$/, "").trim();
    if (!LITERAL_TERM.test(base)) return [];
    out.push(base);
  }
  return out;
}

/**
 * The project's vocabulary, as a sentence a model can act on.
 *
 * The semantic layer reads no config, so a project that declared "everybody
 * here knows what a Deal is" to the deterministic rules was still asked for a
 * gloss by the model. An entry opts in with `semantic: true`.
 */
export function vocabularyForPrompt(set: RuleSet): string {
  const named: string[] = [];
  const patterns: string[] = [];
  for (const entry of set.allow) {
    if (!entry.semantic) continue;
    const terms = vocabularyTerms(entry.pattern);
    if (terms.length) named.push(...terms);
    else patterns.push(entry.pattern);
  }
  if (!named.length && !patterns.length) return "";
  const parts = [...named];
  if (patterns.length) {
    parts.push(`anything matching ${patterns.map((p) => `/${p}/`).join(" or ")}`);
  }
  return (
    "PROJECT VOCABULARY. This project's readers already know these, so never ask for " +
    `a gloss or an explanation of them: ${parts.join(", ")}.`
  );
}

/**
 * The semantic prompt bodies.
 *
 * `{{PROJECT_DIR}}` is a placeholder that `plain-english init` fills in on the
 * adopter's own machine. No absolute path is ever committed here.
 *
 * The shipped ruleset declares no vocabulary, so the templates committed to
 * this repository are unchanged by that section. It appears only in the copies
 * `init` writes into a project that asked for it.
 */
export function renderPrompts(set: RuleSet): Record<string, string> {
  const words = ruleListForPrompt(set);
  const shapes = structureListForPrompt(set);
  const vocabulary = vocabularyForPrompt(set);
  /** The vocabulary paragraph, or nothing, without leaving a blank line. */
  const vocab = vocabulary ? [vocabulary, ""] : [];

  const docs = [
    TXT_BANNER,
    "",
    "You are a plain-English gate for a markdown file about to be written or edited.",
    "",
    "Hook input (contains the tool call, including tool_input.file_path and the content being written):",
    "$ARGUMENTS",
    "",
    "First check tool_input.file_path. Respond immediately with {\"ok\": true} and do no further",
    "judgment if ANY of these hold: the path is not inside {{PROJECT_DIR}}; it does not end in",
    ".md, .markdown or .mdx; its basename is CLAUDE.md or writing-style.md (those two document the",
    "banned terms on purpose as a reference list).",
    "",
    "Otherwise judge ONLY the content or new_string being written. Flag:",
    `- Banned terms: ${words}`,
    `- Sentence shapes: ${shapes}`,
    "",
    ...vocab,
    CALIBRATION,
    "",
    PRECISION,
    "",
    JSON_CONTRACT,
  ].join("\n");

  const github = [
    TXT_BANNER,
    "",
    "You are a plain-English gate for a git or GitHub write action (commit message, PR",
    "description or comment, issue body, release notes) about to run as a shell command.",
    "",
    "Hook input (contains the tool call, including tool_input.command):",
    "$ARGUMENTS",
    "",
    "First check tool_input.command. If it is NOT a 'git commit', 'gh pr create/edit/comment/review',",
    "'gh issue create/edit/comment' or 'gh release create/edit' invocation, respond immediately with",
    '{"ok": true} and do no further judgment. Read-only commands (git log, git status, gh pr view,',
    "ls, grep, npm) are never judged: their output is other people's prose.",
    "",
    "Otherwise judge ONLY the message text the command introduces: the -m/--message value, the",
    "--title/--body value, a heredoc body, or the contents of a file passed with -F/--file/",
    "--body-file/--notes-file. Ignore branch names, flags, file paths and commit hashes. Flag:",
    `- Banned terms: ${words}`,
    `- Sentence shapes: ${shapes}`,
    "",
    ...vocab,
    CALIBRATION,
    "",
    PRECISION,
    "",
    JSON_CONTRACT,
  ].join("\n");

  const issue = [
    TXT_BANNER,
    "",
    "You are a plain-English gate for an issue or comment about to be saved to a tracker.",
    "",
    "Hook input (contains the tool call, including the title and body being written):",
    "$ARGUMENTS",
    "",
    "Judge ONLY the text this call would put in front of a reader: tool_input.title,",
    "tool_input.description, tool_input.body, and the new_string / text fields of any",
    "tool_input.patch entry. Ignore issue IDs, labels and other metadata.",
    "",
    "Do NOT judge tool_input.patch old_string or anchor values. That is existing text being",
    "replaced or located, not text being introduced, so someone fixing one line of an old body",
    "must not be blocked by the rest of it.",
    "",
    "Standard platform terminology for the tools this project uses is assumed vocabulary and does",
    "not need expanding. Only genuinely obscure internal shorthand (project-specific codenames, and",
    "acronyms that are not standard industry or product terms) needs a gloss. Flag:",
    "- Unglossed internal shorthand",
    `- Banned terms: ${words}`,
    `- Sentence shapes: ${shapes}`,
    "",
    ...vocab,
    CALIBRATION,
    "",
    PRECISION,
    "",
    JSON_CONTRACT,
  ].join("\n");

  /**
   * The chat judge.
   *
   * Unlike the other three, this one is not asked to find a fault. The
   * deterministic pass has already found one, and the only question left is
   * whether the reader asked for it. So the default answer here is the
   * opposite of the default answer there: waive, unless the length is doing
   * nothing for the reader.
   *
   * It exists because a word count cannot tell a wall of text from a
   * walkthrough somebody requested, and a check that cannot tell the
   * difference would hold one turn in ten for no reason.
   */
  const chat = [
    TXT_BANNER,
    "",
    "A reply is about to be sent. A word count has already found it long, or found it",
    "carrying many separate names. You decide only whether that was earned.",
    "",
    "Hook input (the reader's last message, then the reply):",
    "$ARGUMENTS",
    "",
    'Return {"ok": true}, waiving the length, if ANY of these hold:',
    ...set.chat.expand.map((e) => `- ${e}`),
    "- The reader asked a question whose honest answer is genuinely this long.",
    "- The bulk of the reply is quoted output, a table, code, or a command to run.",
    "",
    'Return {"ok": false} only when the length buys the reader nothing: the answer is',
    "in there but arrives late, the reply restates the question, it explains what it is",
    "about to do, it covers a second topic nobody asked about, or it names files, keys",
    "and flags where a plain description would do.",
    "",
    "When you refuse, `reason` must say what the reply should have led with, in one",
    "sentence, quoting the line that should have been first.",
    "",
    "Your reason is shown to the reader and goes back to the model, so it is held to the",
    "same rules as the reply. No em dashes: use a comma, parentheses, or a full stop. A",
    "reason that breaks a rule is thrown away and replaced with a bare word count, which",
    "helps nobody.",
    "",
    "CALIBRATION. Waiving is the normal answer and a complete job. The reader would",
    "rather read one long reply they asked for than lose an answer they needed. Refuse",
    "only when a much shorter reply would have served them better.",
    "",
    ...vocab,
    JSON_CONTRACT,
  ].join("\n");

  return { docs, github, issue, chat };
}

export interface RenderTarget {
  path: string;
  content: string;
}

/**
 * The guidance itself, with no host's packaging around it.
 *
 * Shared by the Claude Code output style and the AGENTS.md fragment so the two
 * cannot drift. Everything host-specific is the few lines each wrapper adds.
 *
 * It carries structure and glossing. The deterministic linter keeps owning
 * banned terms, so neither restates the other.
 */
function styleBody(set: RuleSet, level: string): string[] {
  const chat = set.chat;
  const maxWords = set.readability.find((r) => r.kind === "long-sentence")?.maxWords;
  // A placeholder rather than a hardcoded number, so the threshold the style
  // states and the threshold `long-sentence` enforces are the same value.
  const fill = (s: string): string =>
    s.replace(/\{\{maxWords\}\}/g, maxWords === undefined ? "35" : String(maxWords));

  const out: string[] = [];

  if (chat.scope) {
    out.push("## What this applies to", "", ...wrap(fill(chat.scope)), "");
  }

  for (const g of chat.guidance) {
    if (!inLevel(g, level)) continue;
    out.push(`## ${g.name ?? g.id}`, "");
    if (g.description) out.push(...wrap(fill(g.description)), "");
    // Quoted rather than paraphrased. A rule about how to write is easier to
    // follow from one example of each than from another sentence describing
    // the difference.
    if (g.bad) out.push(`Not this: ${g.bad}`);
    if (g.good) out.push(`This: ${g.good}`);
    if (g.bad || g.good) out.push("");
  }

  // The two numbers a reply is measured against, printed with the values the
  // linter actually enforces rather than restated in prose. Every other section
  // here is advice; this one is the only place the style says what will be
  // checked, so it says the number.
  const limits = (chat.limits ?? []).filter((l) => l.severity !== "off");
  if (limits.length) {
    out.push("## Two numbers, and they are checked", "");
    for (const l of limits) {
      if (l.kind === "reply-length" && l.maxWords !== undefined) {
        out.push(
          ...wrap(
            `- Keep a reply under about ${l.maxWords} words of prose. Quoted output does not count. ${l.message ?? ""}`.trim(),
            "  ",
          ),
        );
      }
      if (l.kind === "reader-load" && l.maxTerms !== undefined) {
        out.push(
          ...wrap(
            `- Name at most about ${l.maxTerms} separate files, keys or flags in one reply. ${l.message ?? ""}`.trim(),
            "  ",
          ),
        );
      }
    }
    out.push(
      "",
      ...wrap(
        "Both give way to the exceptions below. A reply that was asked to go deep is not too long, and a check that cannot tell the difference asks before it refuses.",
      ),
      "",
    );
  }

  const tells = chat.tells.filter((t) => t.severity !== "off" && inLevel(t, level));
  if (tells.length) {
    out.push("## Do not open or close with these", "");
    for (const t of tells) {
      const phrases = t.phrases.map((p) => `"${p}"`).join(", ");
      out.push(...wrap(`- ${phrases}. ${t.message ?? ""}`.trim(), "  "));
    }
    out.push("");
  }

  const avoid = chat.avoid.filter((a) => inLevel(a, level));
  if (avoid.length) {
    out.push("## Do not", "");
    for (const a of avoid) out.push(...wrap(`- ${a.text}`, "  "));
    out.push("");
  }

  if (chat.expand.length) {
    out.push("## When to expand instead", "");
    out.push(
      ...wrap(
        "These outrank everything above. A short reply that drops the answer is a " +
          "worse failure than a long one.",
      ),
      "",
    );
    for (const e of chat.expand) out.push(...wrap(`- ${e}`, "  "));
    out.push("");
  }

  // The generator owns the trailing blank line, so every caller gets the same
  // shape and `--check` does not fail on whitespace nobody can see.
  while (out.length && out[out.length - 1] === "") out.pop();
  return out;
}

/**
 * Wrap to the width the rest of this file is written at.
 *
 * The output style is markdown a person reads in a review, and an unwrapped
 * paragraph assembled from YAML arrives as one very long line. `continuation`
 * indents every line after the first, which is what a list item needs.
 */
function wrap(text: string, continuation = "", width = 78): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    const limit = lines.length ? width - continuation.length : width;
    if (candidate.length > limit && line) {
      lines.push(line);
      line = word;
      continue;
    }
    line = candidate;
  }
  if (line) lines.push(line);
  return lines.map((l, i) => (i === 0 ? l : continuation + l));
}

/**
 * The Claude Code output style.
 *
 * The prevention half of the chat channel, and no longer the only half.
 *
 * This comment used to say a hook cannot gate a chat reply. That was true when
 * it was written and is not true now: `Stop` and `SubagentStop` both fire after
 * the reply exists, and a block sends it back to be written again. Observed
 * against Claude Code 2.1.234 on 2026-08-18.
 *
 * So the style is what stops a bad reply being written, and the gate is what
 * catches the ones it does not stop. Neither replaces the other. The style
 * reaches the model every turn and costs nothing; the gate reads one reply and
 * can hold a turn.
 *
 * Select it with `/config`. The standalone `/output-style` command was removed
 * in Claude Code v2.1.91.
 */
export function renderOutputStyle(set: RuleSet, level?: string): string {
  const id = level ?? set.chat.level;
  const meta = set.chat.levels.find((l) => l.id === id);
  return [
    "---",
    `name: ${meta?.name ?? "Plain English"}`,
    `description: ${meta?.description ?? "Lead with the answer, explain a term before naming it, say what needs a decision."}`,
    // Without this, Claude Code drops its built-in software-engineering
    // instructions and the style changes far more than tone.
    "keep-coding-instructions: true",
    "---",
    "",
    "<!-- GENERATED by `plain-english render` from rules/default.yml. Do not edit. -->",
    "",
    ...styleBody(set, id),
    "",
  ].join("\n");
}

/**
 * Where one level's style is written.
 *
 * The default level keeps the unsuffixed name, so an existing install that
 * already selected "Plain English" in `/config` keeps working across this
 * change rather than finding its style renamed out from under it.
 */
export function outputStylePath(set: RuleSet, level: string): string {
  return level === set.chat.level
    ? "integrations/claude-code/output-styles/plain-english.md"
    : `integrations/claude-code/output-styles/plain-english-${level}.md`;
}

/** Markers `init` splices between, so a re-run replaces only what it wrote. */
export const AGENTS_MD_START = "<!-- plain-english:start -->";
export const AGENTS_MD_END = "<!-- plain-english:end -->";

/**
 * The AGENTS.md section.
 *
 * AGENTS.md is the one instructions convention that reaches roughly twenty
 * agents, and it is plain markdown with no schema, so this is the same guidance
 * with a heading instead of frontmatter. It is loaded once per session rather
 * than restated each turn, which makes it weaker than an output style and far
 * more portable.
 *
 * Wrapped in markers because, unlike every other generated file here, this one
 * is spliced into a file the project also writes by hand.
 */
export function renderAgentsFragment(set: RuleSet): string {
  return [
    AGENTS_MD_START,
    "<!-- GENERATED by `plain-english render` from rules/default.yml. Do not edit by hand:",
    "     edit the ruleset and re-run `plain-english init`. -->",
    "",
    "## Writing style",
    "",
    "`plain-english lint` checks every file you write, every commit message, and every",
    "issue or pull request body. Run `npx plain-english lint <file>` after writing",
    "prose, and fix what it reports.",
    "",
    "Everything below is about what you say in chat. A gate on the stop event reads",
    "each reply and can send it back, so this is checked rather than merely asked for.",
    "",
    // One file, so it carries one level. Claude Code gets all of them as
    // separate output styles; every other agent gets the default.
    ...styleBody(set, set.chat.level),
    "",
    AGENTS_MD_END,
    "",
  ].join("\n");
}

export function renderAll(set: RuleSet, root: string): RenderTarget[] {
  const prompts = renderPrompts(set);
  return [
    { path: resolve(root, "docs/writing-style.md"), content: renderWritingStyle(set) },
    {
      path: resolve(root, "integrations/agents-md/plain-english.md"),
      content: renderAgentsFragment(set),
    },
    ...set.chat.levels.map((level) => ({
      path: resolve(root, ...outputStylePath(set, level.id).split("/")),
      content: renderOutputStyle(set, level.id),
    })),
    ...Object.entries(prompts).map(([name, content]) => ({
      path: resolve(root, `integrations/claude-code/prompts/${name}.txt`),
      content,
    })),
  ];
}

/** Write targets to disk. Returns the paths whose contents changed. */
export function writeTargets(targets: RenderTarget[]): string[] {
  const changed: string[] = [];
  for (const t of targets) {
    const existing = existsSync(t.path) ? readFileSync(t.path, "utf8") : null;
    if (existing === t.content) continue;
    mkdirSync(dirname(t.path), { recursive: true });
    writeFileSync(t.path, t.content, "utf8");
    changed.push(t.path);
  }
  return changed;
}
