/**
 * Generate every artifact that restates the rules.
 *
 * The old design maintained the same list in four shapes: a regex in three
 * shell scripts, a prose list inside three prompt bodies, a human-readable
 * table in a markdown file, and a summary in the project instructions. Nothing
 * checked that they agreed, and they did not.
 *
 * Here, only rules/default.yml is written by hand. Everything else is emitted
 * from it and checked by CI.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Rule, RuleSet, Structure } from "./rules.ts";

const BANNER =
  "<!-- GENERATED by `plain-english render` from rules/default.yml. Do not edit. -->\n" +
  // This file lists every banned term as reference material, so it necessarily
  // trips almost every rule. Carrying its own directive means an adopter does
  // not have to discover that and add an `exclude` entry by hand.
  "<!-- plain-english-disable-file -->";
const TXT_BANNER =
  "# GENERATED by `plain-english render` from rules/default.yml. Do not edit.";

/**
 * Turn a rule's regex back into something a human can read.
 *
 *   seamless(ly)?              ->  seamless[ly]
 *   delv(e|es|ed|ing)          ->  delv(e/es/ed/ing)
 *   cutting[- ]edge            ->  cutting-edge
 *   a|b                        ->  a, b
 *
 * An optional group has to be rendered as optional. Collapsing `(ly)?` to `ly`
 * turned "seamless(ly)?" into "seamlessly" in the first generated table, which
 * told the reader the bare word was allowed.
 */
export function humanise(rule: Rule): string {
  const m = rule.match;
  if (m === "—") return "em dash (—)";
  if (m === "\\s–\\s") return "en dash used as a sentence break";

  // Split on alternation at depth 0 only, so `(a|b)` stays intact.
  const alternatives: string[] = [];
  let depth = 0;
  let current = "";
  for (let i = 0; i < m.length; i++) {
    const ch = m[i]!;
    if (ch === "\\") {
      current += ch + (m[++i] ?? "");
      continue;
    }
    if (ch === "(") depth++;
    if (ch === ")") depth--;
    if (ch === "|" && depth === 0) {
      alternatives.push(current);
      current = "";
      continue;
    }
    current += ch;
  }
  alternatives.push(current);

  const render = (alt: string): string =>
    alt
      .replace(/\(\?[=!:][^)]*\)/g, "") // lookarounds carry no reader value
      .replace(/\(([^()]*)\)\?/g, (_, inner: string) => `[${inner.split("|").join("/")}]`)
      .replace(/\(([^()]*)\)/g, (_, inner: string) => {
        const opts = inner.split("|").filter(Boolean);
        return opts.length > 1 ? `(${opts.join("/")})` : inner;
      })
      .replace(/\[- \]/g, "-")
      // An optional literal ("it'?s" catches both spellings) reads as the
      // straight form. Leaving the "?" in makes the table look like regex.
      .replace(/([^)\]?])\?/g, "$1")
      .replace(/\\b/g, "")
      .replace(/\\s\+?/g, " ")
      .replace(/\\([.\-'])/g, "$1")
      .replace(/\\/g, "")
      .replace(/\s+/g, " ")
      .trim();

  return alternatives.map(render).filter(Boolean).join(", ");
}

function severityMark(rule: Rule): string {
  return rule.severity === "warn" ? "warn" : "block";
}

/** docs/writing-style.md */
export function renderWritingStyle(set: RuleSet): string {
  const out: string[] = [];
  out.push(BANNER, "");
  out.push(`# ${set.meta.title}`, "");
  if (set.meta.intro) out.push(set.meta.intro, "");

  out.push("Two severities:", "");
  out.push("| Severity | Effect |");
  out.push("|---|---|");
  out.push("| `block` | The write is refused and the CLI exits non-zero. |");
  out.push(
    "| `warn` | Reported, never blocks. Used for terms with a real technical sense. |",
  );
  out.push("");

  out.push("## Words and phrases", "");
  out.push("| Term | Severity | Instead | Why |");
  out.push("|---|---|---|---|");
  for (const rule of set.rules) {
    if (rule.severity === "off") continue;
    const why = rule.link ? `[notes](${rule.link})` : "";
    out.push(
      `| ${humanise(rule)} | \`${severityMark(rule)}\` | ${rule.message ?? ""} | ${why} |`,
    );
  }
  out.push("");

  const withExceptions = set.rules.filter((r) => r.unless?.length && r.severity !== "off");
  if (withExceptions.length) {
    out.push("## Exceptions", "");
    out.push(
      "These terms have a legitimate technical or domain sense. The listed uses never trigger a finding.",
      "",
    );
    for (const rule of withExceptions) {
      out.push(`- **${rule.id}**: ${rule.unless!.map((u) => `\`${u}\``).join(", ")}`);
    }
    out.push("");
  }

  out.push("## Sentence shapes", "");
  out.push(
    "A word list cannot reach these. They are judged by the semantic layer, or by you.",
    "",
  );
  for (const s of set.structures) {
    out.push(`### ${s.name}`, "");
    out.push(s.description, "");
    if (s.bad) out.push(`Bad: ${s.bad}`);
    if (s.good) out.push(`Good: ${s.good}`);
    out.push("");
  }

  out.push("## What is never scanned", "");
  out.push(
    "Fenced and indented code, inline code spans, YAML frontmatter, blockquotes, URLs, link targets and email addresses are blanked before matching. A banned term inside any of those is not a finding.",
    "",
  );
  out.push("## Suppressing a finding", "");
  out.push("```markdown");
  out.push("<!-- plain-english-disable-next-line leverage -->");
  out.push("<!-- plain-english-disable-file -->");
  out.push("```");
  out.push("");
  out.push(
    "Or add the path to `exclude` in `.plain-english.yml`, or lower the rule to `severity: warn`.",
    "",
  );

  return out.join("\n");
}

function ruleListForPrompt(set: RuleSet): string {
  const blocking = set.rules
    .filter((r) => r.severity === "error")
    .map((r) => humanise(r));
  return blocking.join("; ");
}

function structureListForPrompt(set: RuleSet): string {
  return set.structures.map((s) => `${s.name} (${s.description.replace(/\s+/g, " ").trim()})`).join("; ");
}

const JSON_CONTRACT =
  'Respond with ONLY JSON, nothing else: {"ok": true} if it passes, or ' +
  '{"ok": false, "reason": "<quote the offending substring verbatim, then give a one-line plain rewrite>"} if it does not.';

/**
 * Calibration.
 *
 * Asked to find a list of patterns, a model finds patterns. Observed in this
 * project before these rules existed: one document was refused twelve times in
 * a row; on two of those the model flagged wording it had itself proposed one
 * turn earlier; on another it reasoned to the conclusion that no violation
 * existed and returned a refusal anyway.
 *
 * The three rules below target those failures directly. The self-consistency
 * rule is the important one: a verdict whose own reasoning says the text is
 * fine must be a pass.
 */
const CALIBRATION =
  "CALIBRATION. Most text you see is fine. A pass is the normal answer, and returning one is " +
  'a correct, complete job. Do not go looking for something to flag.\n\n' +
  "SELF-CONSISTENCY. If your reasoning arrives at the conclusion that the text is acceptable, " +
  'you MUST return {"ok": true}. Never return a failure whose reason says the content passes, ' +
  "says no violation was found, or hedges about whether a rule applies. A failure means you " +
  "located a specific, quotable problem and are certain about it.\n\n" +
  "ONE FLAG. Report the single clearest problem. Do not accumulate borderline observations, " +
  "and do not flag a phrase you would accept if you saw it in a well-edited document.\n\n" +
  "NO SECOND-GUESSING A REWRITE. If the text reads as a plain, direct statement of fact, it " +
  "passes, even if you can imagine a different phrasing.";

const PRECISION =
  "Before writing your reason, quote the exact substring from the text that triggered it. " +
  "If you cannot find that substring verbatim in the text, do not flag it. " +
  "The deterministic linter has already checked every banned term and blocked the write if it " +
  "found one, so a term reaching you has already passed that check: judge SENTENCE SHAPES, and " +
  "flag a listed term only when it is genuinely being used as the tell rather than as ordinary " +
  "domain vocabulary. " +
  "Do NOT flag: exact technical identifiers that must stay verbatim, text inside code blocks or " +
  "inline code, quoted third-party text in blockquotes, URLs, normal concise writing, or " +
  "stylistic choices outside this list. Be precise, not paranoid.";

/**
 * The semantic prompt bodies.
 *
 * `{{PROJECT_DIR}}` is a placeholder that `plain-english init` fills in on the
 * adopter's own machine. No absolute path is ever committed here.
 */
export function renderPrompts(set: RuleSet): Record<string, string> {
  const words = ruleListForPrompt(set);
  const shapes = structureListForPrompt(set);

  const docs = [
    TXT_BANNER,
    "",
    "You are a plain-English gate for a markdown file about to be written or edited.",
    "",
    "Hook input (contains the tool call, including tool_input.file_path and the content being written):",
    "$ARGUMENTS",
    "",
    "First check tool_input.file_path. Respond immediately with {\"ok\": true} and do no further",
    "judgment if ANY of these hold: the path is not inside {{PROJECT_DIR}}; it does not end in",
    ".md, .markdown or .mdx; its basename is CLAUDE.md or writing-style.md (those two document the",
    "banned terms on purpose as a reference list).",
    "",
    "Otherwise judge ONLY the content or new_string being written. Flag:",
    `- Banned terms: ${words}`,
    `- Sentence shapes: ${shapes}`,
    "",
    CALIBRATION,
    "",
    PRECISION,
    "",
    JSON_CONTRACT,
  ].join("\n");

  const github = [
    TXT_BANNER,
    "",
    "You are a plain-English gate for a git or GitHub write action (commit message, PR",
    "description or comment, issue body, release notes) about to run as a shell command.",
    "",
    "Hook input (contains the tool call, including tool_input.command):",
    "$ARGUMENTS",
    "",
    "First check tool_input.command. If it is NOT a 'git commit', 'gh pr create/edit/comment/review',",
    "'gh issue create/edit/comment' or 'gh release create/edit' invocation, respond immediately with",
    '{"ok": true} and do no further judgment. Read-only commands (git log, git status, gh pr view,',
    "ls, grep, npm) are never judged: their output is other people's prose.",
    "",
    "Otherwise judge ONLY the message text the command introduces: the -m/--message value, the",
    "--title/--body value, a heredoc body, or the contents of a file passed with -F/--file/",
    "--body-file/--notes-file. Ignore branch names, flags, file paths and commit hashes. Flag:",
    `- Banned terms: ${words}`,
    `- Sentence shapes: ${shapes}`,
    "",
    CALIBRATION,
    "",
    PRECISION,
    "",
    JSON_CONTRACT,
  ].join("\n");

  const issue = [
    TXT_BANNER,
    "",
    "You are a plain-English gate for an issue or comment about to be saved to a tracker.",
    "",
    "Hook input (contains the tool call, including the title and body being written):",
    "$ARGUMENTS",
    "",
    "Judge ONLY the text this call would put in front of a reader: tool_input.title,",
    "tool_input.description, tool_input.body, and the new_string / text fields of any",
    "tool_input.patch entry. Ignore issue IDs, labels and other metadata.",
    "",
    "Do NOT judge tool_input.patch old_string or anchor values. That is existing text being",
    "replaced or located, not text being introduced, so someone fixing one line of an old body",
    "must not be blocked by the rest of it.",
    "",
    "Standard platform terminology for the tools this project uses is assumed vocabulary and does",
    "not need expanding. Only genuinely obscure internal shorthand (project-specific codenames, and",
    "acronyms that are not standard industry or product terms) needs a gloss. Flag:",
    "- Unglossed internal shorthand",
    `- Banned terms: ${words}`,
    `- Sentence shapes: ${shapes}`,
    "",
    CALIBRATION,
    "",
    PRECISION,
    "",
    JSON_CONTRACT,
  ].join("\n");

  return { docs, github, issue };
}

export interface RenderTarget {
  path: string;
  content: string;
}

/**
 * The Claude Code output style.
 *
 * This is the only artifact that reaches chat. A hook cannot gate a reply:
 * nothing sits between the text being written and somebody reading it. An
 * output style is appended to the system prompt and re-stated to the model each
 * turn, which makes it the strongest lever available, and still a prompt.
 *
 * It carries structure and glossing. The deterministic linter keeps owning
 * banned terms, so neither restates the other.
 */
export function renderOutputStyle(set: RuleSet): string {
  const maxWords = set.readability.find((r) => r.kind === "long-sentence")?.maxWords;

  return [
    "---",
    "name: Plain English",
    "description: Lead with the subject, explain a term before naming it, say what needs a decision.",
    // Without this, Claude Code drops its built-in software-engineering
    // instructions and the style changes far more than tone.
    "keep-coding-instructions: true",
    "---",
    "",
    "<!-- GENERATED by `plain-english render` from rules/default.yml. Do not edit. -->",
    "",
    "## Open with what this is",
    "",
    "The first line names the subject and says whether this is a result, a problem,",
    "or a question. No preamble, no restating the request.",
    "",
    "## Explain a thing before naming it",
    "",
    "Give the plain description first, then the technical term, so the name lands on",
    "something the reader already understands.",
    "",
    "> GitHub signs a receipt proving where the code came from. That receipt is",
    "> called provenance.",
    "",
    "Not the reverse. An acronym introduced before its explanation makes the reader",
    "carry an unknown through the rest of the sentence.",
    "",
    "## Say what needs a decision",
    "",
    "When a reply contains a choice, end with what the reader has to decide and what",
    "each option costs. When nothing is needed from them, say that too, so silence",
    "never has to be interpreted.",
    "",
    "## Depth is welcome, unexplained depth is not",
    "",
    "Technical detail is the point of the conversation. Keep it. The failure mode is",
    "a term nobody defined, not a subject that is hard.",
    "",
    maxWords !== undefined
      ? `Long sentences are fine when they carry one idea. Past about ${maxWords} words they` +
        "\nusually carry three, so split them."
      : "Long sentences are fine when they carry one idea. Split them when they carry three.",
    "",
    "## Do not",
    "",
    "- Open with a summary of what was just asked.",
    "- Announce structure (\"I will first explain, then show\"). Just do it.",
    "- Claim something is done without having checked.",
    "- Bury the decision in the middle of a paragraph.",
    "",
  ].join("\n");
}

export function renderAll(set: RuleSet, root: string): RenderTarget[] {
  const prompts = renderPrompts(set);
  return [
    { path: resolve(root, "docs/writing-style.md"), content: renderWritingStyle(set) },
    {
      path: resolve(root, "integrations/claude-code/output-styles/plain-english.md"),
      content: renderOutputStyle(set),
    },
    ...Object.entries(prompts).map(([name, content]) => ({
      path: resolve(root, `integrations/claude-code/prompts/${name}.txt`),
      content,
    })),
  ];
}

/** Write targets to disk. Returns the paths whose contents changed. */
export function writeTargets(targets: RenderTarget[]): string[] {
  const changed: string[] = [];
  for (const t of targets) {
    const existing = existsSync(t.path) ? readFileSync(t.path, "utf8") : null;
    if (existing === t.content) continue;
    mkdirSync(dirname(t.path), { recursive: true });
    writeFileSync(t.path, t.content, "utf8");
    changed.push(t.path);
  }
  return changed;
}
